services:

  postgres_db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env        # POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 12


  flyway:
    image: flyway/flyway:10-alpine
    container_name: flyway
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres_db:5432/${POSTGRES_DB}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}

      FLYWAY_PLACEHOLDERS_APP_USER_NAME: ${APP_DB_USER}
      FLYWAY_PLACEHOLDERS_APP_USER_PASSWORD: ${APP_DB_PASSWORD}
      FLYWAY_PLACEHOLDERS_DB_ADMIN_NAME: ${DB_ADMIN_USER}
      FLYWAY_PLACEHOLDERS_DB_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD}

      FLYWAY_BASELINE_ON_MIGRATE: "true"
      FLYWAY_CLEAN_DISABLED: "true"
      FLYWAY_GROUP: "true"
    volumes:
      - ./db/migration:/flyway/sql
    command: migrate


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - .env        # PGADMIN_DEFAULT_EMAIL, PGADMIN_DEFAULT_PASSWORD
    ports:
      - "8080:80"
    depends_on:
      postgres_db:
        condition: service_healthy


  back:
    image: 'backend'
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - postgres_db
    env_file:
      - .env  # expects POSTGRES_PORT, JWT_SECRET_KEY, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, OPENAI_API_KEY, LOGGING_LEVEL, POSTGRES_HOST
    environment:
      - LOGGING_LEVEL=DEBUG
    ports:
      - "8082:8082"
    healthcheck:
      test: if [ "$(curl --silent http://localhost:8082/actuator/health/readiness |  jq -r .status)" = 'UP' ]; then exit 0; else exit 1; fi;
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
