name: DB - Validate & Migrate

on:
  push:
    paths: ["db/**"]
  pull_request:
    paths: ["db/**"]
  workflow_dispatch: {}

jobs:
  flyway:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d mydb"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=30

    env:
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb

      APP_DB_USER: app_user
      DB_ADMIN_USER: db_admin

      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      APP_DB_PASSWORD: ${{ secrets.APP_DB_PASSWORD }}
      DB_ADMIN_PASSWORD: ${{ secrets.DB_ADMIN_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Wait for Postgres
        run: |
          for i in {1..60}; do
            pg_isready -h localhost -p 5432 -U postgres >/dev/null 2>&1 && exit 0
            sleep 1
          done
          echo "Postgres is not ready" && exit 1

      # ✅ MIGRATE — через обычный docker run
      - name: Flyway migrate
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}/db/migration:/flyway/sql \
            flyway/flyway:10-alpine \
            -url=jdbc:postgresql://localhost:5432/mydb \
            -user=postgres \
            -password=$POSTGRES_PASSWORD \
            -connectRetries=60 \
            -baselineOnMigrate=true \
            -cleanDisabled=true \
            -group=true \
            -placeholders.app_user_name=$APP_DB_USER \
            -placeholders.app_user_password=$APP_DB_PASSWORD \
            -placeholders.db_admin_name=$DB_ADMIN_USER \
            -placeholders.db_admin_password=$DB_ADMIN_PASSWORD \
            migrate

      - name: Flyway validate
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}/db/migration:/flyway/sql \
            flyway/flyway:10-alpine \
            -url=jdbc:postgresql://localhost:5432/mydb \
            -user=postgres \
            -password=$POSTGRES_PASSWORD \
            validate
