name: infra-backend (apply + run migrations)

on:
  workflow_dispatch:
    inputs:
      action:
        description: "plan, apply, or destroy"
        required: true
        default: "plan"
        type: choice
        options: [plan, apply, destroy]
      backend_image:
        description: "ECR image URI for backend (repo:tag)"
        required: true
        type: string
      flyway_image:
        description: "ECR image URI for flyway-migrations (repo:tag)"
        required: true
        type: string
      vpc_id:
        description: "vpc_id"
        required: true
        type: string
      db_secret_arn:
        description: "db_secret_arn"
        required: true
        type: string
      cluster_name:
        description: "cluster_name"
        required: true
        type: string
      alb_listener_arn:
        description: "alb_listener_arn"
        required: true
        type: string
      backend_sg_id:
        description: "backend_sg_id"
        required: true
        type: string
      private_subnet_ids:
        required: true
        type: string
        description: 'JSON list, e.g. ["subnet-aaa","subnet-bbb"]'


permissions:
  id-token: write
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      TF_VAR_jwt_secret_key: ${{ secrets.JWT_SECRET_KEY }}
      TF_VAR_google_client_id: ${{ secrets.GOOGLE_CLIENT_ID }}
      TF_VAR_google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::423161708569:role/GitHubActionsTerraformCoreRole
          aws-region: eu-north-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Init
        working-directory: infra/backend
        run: terraform init

      - name: Validate
        working-directory: infra/backend
        run: terraform validate

      - name: Plan
        if: inputs.action == 'plan'
        working-directory: infra/backend
        run: |
          terraform plan \
            -var="backend_image=${{ inputs.backend_image }}" \
            -var="flyway_image=${{ inputs.flyway_image }}" \
            -var="backend_image=${{ inputs.backend_image }}" \
            -var="flyway_image=${{ inputs.flyway_image }}" \
            -var="vpc_id=${{ inputs.vpc_id }}" \
            -var="db_secret_arn=${{ inputs.db_secret_arn }}" \
            -var="cluster_name=${{ inputs.cluster_name }}" \
            -var="alb_listener_arn=${{ inputs.alb_listener_arn }}" \
            -var="backend_sg_id=${{ inputs.backend_sg_id }}" \
            -var='private_subnet_ids=${{ inputs.private_subnet_ids }}'

      - name: Apply
        if: inputs.action == 'apply'
        working-directory: infra/backend
        run: |
          terraform apply -auto-approve \
            -var="backend_image=${{ inputs.backend_image }}" \
            -var="flyway_image=${{ inputs.flyway_image }}" \
            -var="backend_image=${{ inputs.backend_image }}" \
            -var="flyway_image=${{ inputs.flyway_image }}" \
            -var="vpc_id=${{ inputs.vpc_id }}" \
            -var="db_secret_arn=${{ inputs.db_secret_arn }}" \
            -var="cluster_name=${{ inputs.cluster_name }}" \
            -var="alb_listener_arn=${{ inputs.alb_listener_arn }}" \
            -var="backend_sg_id=${{ inputs.backend_sg_id }}" \
            -var='private_subnet_ids=${{ inputs.private_subnet_ids }}'

      - name: Destroy
        if: ${{ inputs.action == 'destroy' }}
        working-directory: infra/backend
        run: |
            terraform destroy -auto-approve \
              -var="backend_image=${{ inputs.backend_image }}" \
              -var="flyway_image=${{ inputs.flyway_image }}" \
              -var="backend_image=${{ inputs.backend_image }}" \
              -var="flyway_image=${{ inputs.flyway_image }}" \
              -var="vpc_id=${{ inputs.vpc_id }}" \
              -var="db_secret_arn=${{ inputs.db_secret_arn }}" \
              -var="cluster_name=${{ inputs.cluster_name }}" \
              -var="alb_listener_arn=${{ inputs.alb_listener_arn }}" \
              -var="backend_sg_id=${{ inputs.backend_sg_id }}" \
              -var='private_subnet_ids=${{ inputs.private_subnet_ids }}'